language: node_js
node_js:
  - "0.10"
env:
  - t=unit
  - t=integration
  - r=KARMA t=integration
  - r=KARMA t=unit
matrix:
  # just run unit tests on old node versions
  include:
    - node_js: "0.8"
      env: t=unit
    - node_js: "0.6"
      env: t=unit
    - node_js: "0.11"
      env: t=unit
  
  # integration tests shouldn't fail the build, as they're often rate-limit issues
  allow_failures:
    - node_js: "0.10"
      env: t=integration
    - node_js: "0.10"
      env: r=KARMA t=integration
    - node_js: "0.11"
      env: t=unit
notifications:
  email: false
script: "./tools/bin/travis-tests"
